language: objective-c
before_script:
    - brew update
    - brew install xctool && brew cleanup xctool
    - gem install cocoapods
script:
    - cd NitroMisc
    - pod install
    - xctool -workspace NitroMisc.xcworkspace -sdk iphonesimulator -scheme NitroMisc test GCC_PREPROCESSOR_DEFINITIONS="TESTS_XCTOOL_STDERR_REDIRECT_BUG=1 TESTS_CREATE_DOCS_DIR=1"
