language: objective-c
script:
    - cd NitroMisc
    - pod install
    - xcodebuild -workspace NitroMisc.xcworkspace -sdk iphonesimulator -scheme NitroMisc test GCC_PREPROCESSOR_DEFINITIONS="TESTS_XCTOOL_STDERR_REDIRECT_BUG=1 TESTS_CREATE_DOCS_DIR=1"
